# Generated by Django 2.0.3 on 2018-03-29 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20180330_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='genre',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='guide.Genre'),
            preserve_default=False,
        ),
    ]
