# Generated by Django 2.0.4 on 2018-04-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20180425_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementmember',
            name='inviter',
        ),
        migrations.RemoveField(
            model_name='gamemember',
            name='inviter',
        ),
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Logo'),
        ),
    ]
