# Generated by Django 2.0.3 on 2018-03-29 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_image_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='level',
            new_name='mptt_level',
        ),
    ]
