# Generated by Django 2.0.4 on 2018-04-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_auto_20180426_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemember',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamemember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='game',
            name='members',
        ),
        migrations.AddField(
            model_name='user',
            name='game',
            field=models.ManyToManyField(to='guide.Game'),
        ),
        migrations.DeleteModel(
            name='GameMember',
        ),
    ]
