# Generated by Django 2.0.4 on 2018-04-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_auto_20180427_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementmember',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='achievementmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='members',
        ),
        migrations.AddField(
            model_name='achievement',
            name='condition',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='achievement',
            field=models.ManyToManyField(to='guide.Achievement'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='AchievementMember',
        ),
    ]
