# Generated by Django 2.0.4 on 2018-04-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_auto_20180427_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='achievement',
            field=models.ManyToManyField(null=True, to='guide.Achievement'),
        ),
        migrations.AlterField(
            model_name='user',
            name='game',
            field=models.ManyToManyField(null=True, to='guide.Game'),
        ),
    ]
