# Generated by Django 2.0.3 on 2018-03-29 19:44

from django.db import migrations, models
import guide.models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_auto_20180330_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=guide.models.upload_location),
        ),
    ]
