# Generated by Django 2.0.3 on 2018-03-29 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_auto_20180330_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='guide.Genre'),
        ),
    ]
